branches:
  ignore:
  - master
  - release
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
git:
  quiet: true
language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/m2/repository"
  - "$HOME/.android"
  - ".gradle"
  - ".ci/vendor/bundle"
android:
  components:
  - platform-tools
  - android-28
  - build-tools-28.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  - tools
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- ./gradlew androidDependenciesExtra dependencies

env:
  global:
    - JUNIT_TEST_RESULT_DIR: test-results/junit
    - JUNIT_TEST_REPORT_DIR: test-reports/
    - secure: "RjEhQS1WRdrve8jJ9vPdPBklwH/4FW5enkqrD9/uQaVp6O4wCSxsxDDD8tCeX1fKyuh5NskFoebQ/9ez+uPcG4cFOq8+3JQ0Ym1iAunMf6ViAJiiYEoMVFfJq3CpSp79KKg/bpbIdg3ADIqhUgOwtD3SOUly1F2Uvw4UUqRRNiYAjdNLNwCxAs+wCDhJIAEyo2/XjIzt9O6ivyKhTfmz3vg+zyJundHhMyU/FytF/NxfqKcLnle1jjQ1AQAcZKYWw9ITZqJFrxHsMMgT5vf1zmoMmx1U+j6NvOb8UM4L1bxq0+m6KAVLOO+ZOnnnJBcdNvENJDB+Nwk5bNf7ovW+m+39Z/kHK/GxQHUDApuwcSOSYaB4NVToH5+6TlAWq6al2XjRDAjyI6t4hwy5bk4wZHYNQ78ZGL0Paapuf5tf0wZNXjX78Ob+ayZAhcendUTBvspfL3L76C2fdJgFPq5eupcC4IpQ88Np+/LXUnDfnphBPKBdwBjjW0ijMsfe0XXRiRcgpyAU5uIwB+NeDk8bIdsWup/KMc8hFWCvnWT28YHmToX8cC13OlGcy3RejcD2vC2/2mdEVqxOGdexrckTZBMnPrbq4pUFqLFf4Bz7OP2ACvbibOFxGd6WnNyUvwDowhaB2qnmw9ZcLafmVRTlkGdXOcCHBSjdzbJByjcqPqU="
    - secure: "Kq6RyNujzy141Xvut0gDlTsX/ZxW3skL6o0JcCvjUPEol2ppZ9ngaXqz+11MmjcyZUHaqispmB1VxQIPqiw06EXMFzSqoivtlJOslDJzvBovqaYdXPt+95G7HJCRy9ClHeIserUfBhPvYryx+II/yB2K3pJQfpJoN+lYRtVuRg9q2/eQ6GA/7Wu6iM1ZYnJDehfLM/9uVSLx9Irsc8EN18IAsTBXU06lmgt82Z7nC2DDQ4S3H7xkcGZauYsM5v1eVJ6INaM3NS+2Hp0Sz1HlQGWrL8uw/wipcBfVy1rgd93QedZdF1J8Gr4Y5CqldcWGo4uoKVOdTOYwY1xY4gDkzz+cGAi+QzTTODhGtpfOiQht0En+YNZ9fnUwPQMsTd2S5sbup9fT2dbQloyG5zyGqLJQqX9xVLVOmXQewVoolACuuERDS9h9ZdD2HOxWu8uKaOklkRf2248QMJW7Yl1bqSBvmJ2wxX4Q5RqFGJGbupfC4ITinGcYFbxv2rLd56JG53dBk2Hwzdc1lOR0zdkI9mJAQzosnbrbS0p/rFHpxS0Rlfv9a+zSAbFcdCOOXIhmismiWHwk65jAqNcVGzzCiNxWggnTonePa88iW2DViVzwHrW29d6eNau9qxwZqPa+TM5R5LtRmAvbpfDAtkB5rCeocjtD2yTy+64uB7kFYac="
jobs:
  include:
    - stage: build-and-deploy
      script: ./gradlew android-base:assembleDebug --offline
      deploy:
        provider: script
        script: ./.travis/android/deploy.bash
        on:
          all_branches: true
          tags: false
          condition: "! $TRAVIS_BRANCH =~ ^(master|release)$"
        skip_cleanup: true
    - stage: test
      script:
        - ./gradlew lintDebug testDebug ktlint --continue || true
        - ./.ci/scripts/collect-test-artifacts.bash
        - ./.travis/android/danger.bash
